version: "3.8"
services:
  charger:
    depends_on:
      - storage
    build: ./charger
    ports:
      - "3001:3001"
    environment:
      - "REDIS_URL=redis://storage:6379/15"
      - "RABBITMQ_URL=amqp://messaging:5672"
      - "REDIS_PROVIDER=REDIS_URL"
  fetcher:
    depends_on:
      - storage
      - messaging
    build: ./charger
    entrypoint: ["bundle", "exec", "sidekiq"]
    environment:
      - "REDIS_URL=redis://storage:6379/15"
      - "RABBITMQ_URL=amqp://messaging:5672"
      - "REDIS_PROVIDER=REDIS_URL"
  storage:
    image: redis:6.0.3-alpine3.11
    ports:
      - "6400:6379"
  messaging:
    image: rabbitmq:3.8.4-alpine
    ports:
      - "5600:5672"
