version: "3.8"
services:
  charger:
    depends_on:
      - storage
      - messaging
    build: ./charger
    restart: on-failure
    entrypoint: ["/app/start.sh", "rails s"]
    ports:
      - "3001:3001"
    environment:
      - "REDIS_URL=redis://storage:6379/15"
      - "RABBITMQ_URL=amqp://messaging:5672"
      - "REDIS_PROVIDER=REDIS_URL"
  fetcher:
    depends_on:
      - storage
      - messaging
    build: ./charger
    restart: on-failure
    entrypoint: ["/app/start.sh", "bundle exec sidekiq"]
    environment:
      - "REDIS_URL=redis://storage:6379/15"
      - "RABBITMQ_URL=amqp://messaging:5672"
      - "REDIS_PROVIDER=REDIS_URL"
      - "FETCHER_TWT_API_KEY=${FETCHER_TWT_API_KEY}"
      - "FETCHER_TWT_API_SECRET=${FETCHER_TWT_API_SECRET}"
      - "FETCHER_TWT_ACCESS_TOKEN=${FETCHER_TWT_ACCESS_TOKEN}"
      - "FETCHER_TWT_ACCESS_TOKEN_SECRET=${FETCHER_TWT_ACCESS_TOKEN_SECRET}"
  blaster:
    depends_on:
      - messaging
    build: ./blaster
    restart: on-failure
    entrypoint: ["/app/start.sh", "bundle exec rake sneakers:run"]
    environment:
      - "RABBITMQ_URL=amqp://messaging:5672"
      - "WORKERS=EmailWorker"
  storage:
    image: redis:6.0.3-alpine3.11
    ports:
      - "6400:6379"
  messaging:
    image: rabbitmq:3.8.4-alpine
    ports:
      - "5600:5672"
